disease_list_all = [
    'Appendicitis',
'Arbovirus Infections',
'Arrhythmias, Cardiac',
'Arterial Occlusive Diseases',
'Arteriosclerosis',
'Arteritis',
'Arthralgia',
'Arthritis',
'Arthritis, Juvenile',
'Arthritis, Psoriatic',
'Arthritis, Rheumatoid',
'Aspergillosis',
'Asthma',
'Astrocytoma',
'Asymptomatic Diseases',
'Asymptomatic Infections',
'Atherosclerosis',
'Atrial Fibrillation',
'Atrioventricular Block',
'Atrophy',
'Attention Deficit and Disruptive Behavior Disorders',
'Attention Deficit Disorder with Hyperactivity',
'Autism Spectrum Disorder',
'Autistic Disorder',
'Autoimmune Diseases',
'Autoimmune Diseases of the Nervous System',
'Autonomic Nervous System Diseases',
'Avitaminosis',
'B-cell Lymphoma',
'Bacteremia',
'Bacterial Infections',
'Bacterial Meningitis',
'Barotrauma',
'Basal Ganglia Diseases',
'BehÃ§et Disease',
'Behavior, Addictive',
'Behavioral Symptoms',
'Behcet Syndrome',
'beta-Thalassemia',
'Bile Duct Cancer',
'Bile Duct Diseases',
'Biliary Tract Cancer',
'Biliary Tract Diseases',
'Binge-Eating Disorder',
'Bipolar and Related Disorders',
'Bipolar Disorder',
'Blister',
'Blood Coagulation Disorders',
'Blood Coagulation Disorders, Inherited',
'Blood Platelet Disorders',
'Blood Protein Disorders',
'Body Temperature Changes',
'Body Weight',
'Body Weight Changes',
'Bone Diseases',
'Bone Diseases, Metabolic',
'Bone Marrow Diseases',
'Bradycardia',
'Brain Damage, Chronic',
'Brain Diseases',
'Brain Injuries',
'Brain Injuries, Traumatic',
'Brain Injury, Chronic',
'Breast Diseases',
'Breast Neoplasms',
'Bronchial Diseases',
'Bronchiectasis',
'Bronchiolitis Obliterans Organizing Pneumonia',
'Bronchopulmonary Dysplasia',
'Brucellosis',
'Bulimia',
'Burnout, Professional',
'Burnout, Psychological',
'Burns',
'Carcinoma',
'Carcinoma, Hepatocellular',
'Carcinoma, Non-Small-Cell Lung',
'Carcinoma, Ovarian Epithelial',
'Carcinoma, Renal Cell',
'Carcinoma, Transitional Cell',
'Cardiac Conduction System Disease',
'Cardiomyopathies',
'Cardiovascular Abnormalities',
'Cartilage Diseases',
'Cataract',
'Cecal Diseases',
'Cellulitis',
'Central Nervous System Bacterial Infections',
'Central Nervous System Diseases',
'Central Nervous System Infections',
'Central Nervous System Neoplasms',
'Cerebral Hemorrhage',
'Cerebral Palsy',
'Cerebrovascular Disorders',
'Chemically-Induced Disorders',
'Chest Pain',
'Chickenpox',
'Chilblains',
'Child Development Disorders, Pervasive',
'Childhood Acute Lymphoblastic Leukemia',
'Cholangiocarcinoma',
'Cholangitis',
'Cholecystitis',
'Cholecystitis, Acute',
'Cholestasis',
'Cholestasis, Intrahepatic',
'Chromosome Disorders',
'Chronic Disease',
'Chronic Lymphocytic Leukemia',
'Chronic Myeloproliferative Disorders',
'Chronic Pain',
'Chronic Traumatic Encephalopathy',
'Clear Cell Renal Cell Carcinoma',
'Clinical Deterioration',
'Coagulation Protein Disorders',
'Cognition Disorders',
'Cognitive Dysfunction',
'Coinfection',
'Colitis',
'Colitis, Ulcerative',
'Collagen Diseases',
'Colonic Diseases',
'Colonic Neoplasms',
'Colonic Polyps',
'Colorectal Neoplasms',
'Coma',
'Common Cold',
'Communicable Diseases',
'Communicable Diseases, Emerging',
'Compassion Fatigue',
'Compulsive Behavior',
'Confusion',
'Congenital Abnormalities',
'Conjunctival Diseases',
'Conjunctivitis',
'Conjunctivitis, Viral',
'Connective Tissue Diseases',
'Consciousness Disorders',
'Constriction, Pathologic',
'Convalescence',
'Conversion Disorder',
'Corneal Diseases',
'Coronary Artery Disease',
'Coronary Disease',
'Coronaviridae Infections',
'Coronavirus Infections',
'Corynebacterium Infections',
'Cough',
'Cranial Nerve Diseases',
'Craniocerebral Trauma',
'Craniofacial Abnormalities',
'Critical Illness',
'Crohn Disease',
'Cross Infection',
'Cystic Fibrosis',
'Cysts',
'Deafness',
'Death',
'Death, Sudden',
'Death, Sudden, Cardiac',
'Deficiency Diseases',
'Deglutition Disorders',
'Delirium',
'Dementia',
'Demyelinating Autoimmune Diseases, CNS',
'Demyelinating Diseases',
'Depression',
'Depression, Postpartum',
'Depressive Disorder',
'Depressive Disorder, Major',
'Depressive Disorder, Treatment-Resistant',
'Dermatitis',
'Developmental Disabilities',
'Diabetes Mellitus',
'Diabetes Mellitus, Type 1',
'Diabetes Mellitus, Type 2',
'Diabetic Ketoacidosis',
'Diarrhea',
'DiGeorge Syndrome',
'Digestive System Abnormalities',
'Digestive System Diseases',
'Digestive System Neoplasms',
'Diphtheria',
'Disease Attributes',
'Disease Progression',
'Disease Susceptibility',
'Disseminated Intravascular Coagulation',
'Dissociative Disorders',
'DNA Virus Infections',
'Down Syndrome',
'Drinking Behavior',
'Drug Overdose',
'Drug-Related Side Effects and Adverse Reactions',
'Dry Eye Syndromes',
'Dysgeusia',
'Dyskinesias',
'Dyspareunia',
'Dysphonia',
'Dyspnea',
'Dyssomnias',
'Ear Diseases',
'Eclampsia',
'Eczema',
'Edema',
'Embolism',
'Embolism and Thrombosis',
'Emergence Delirium',
'Emergencies',
'Emphysema',
'Encephalitis',
'Encephalomyelitis',
'Endocrine Gland Neoplasms',
'Endocrine System Diseases',
'Endometrial Neoplasms',
'Endometriosis',
'Endophthalmitis',
'Endotoxemia',
'Eosinophilia',
'Epilepsy',
'Esophageal and Gastric Varices',
'Esophageal Cancer',
'Esophageal Diseases',
'Esophageal Motility Disorders',
'Esophageal Neoplasms',
'Esophageal Spasm, Diffuse',
'Exanthema',
'Eye Diseases',
'Eye Infections',
'Eye Infections, Viral',
'Facial Injuries',
'Facial Pain',
'Facies',
'Familial Alzheimer Disease',
'Familial Mediterranean Fever',
'Fatigue',
'Fatigue Syndrome, Chronic',
'Fatty Liver',
'Feeding and Eating Disorders',
'Femoral Fractures',
'Femoral Neck Fractures',
'Fetal Death',
'Fetal Diseases',
'Fetal Growth Retardation',
'Fetal Membranes, Premature Rupture',
'Fever',
'Fibromyalgia',
'Fibrosis',
'Flaviviridae Infections',
'Flavivirus Infections',
'Fractures, Bone',
'Fractures, Closed',
'Fractures, Stress',
'Frailty',
'Frostbite',
'Gallbladder Diseases',
'Ganglion Cysts',
'Gangrene',
'Gastroenteritis',
'Gastroesophageal Reflux',
'Gastrointestinal Diseases',
'Gastrointestinal Neoplasms',
'Genetic Diseases, Inborn',
'Genetic Predisposition to Disease',
'Genital Neoplasms, Female',
'Genital Neoplasms, Male',
'Gestational Weight Gain',
'Giant Cell Arteritis',
'Glaucoma',
'Glioblastoma',
'Glioma',
'Glucose Intolerance',
'Glucose Metabolism Disorders',
'Gonadal Disorders',
'Gout',
'Gram-Negative Bacterial Infections',
'Gram-Positive Bacterial Infections',
'Growth Disorders',
'Hair Diseases',
'Head and Neck Neoplasms',
'Headache',
'Headache Disorders',
'Headache Disorders, Primary',
'Headache Disorders, Secondary',
'Healthcare-Associated Pneumonia',
'Hearing Disorders',
'Hearing Loss',
'Hearing Loss, Conductive',
'Heart Arrest',
'Heart Block',
'Heart Defects, Congenital',
'Heart Diseases',
'Heart Failure',
'Heart Failure, Systolic',
'Heart Valve Diseases',
'Hemarthrosis',
'Hematologic Diseases',
'Hematologic Neoplasms',
'Hemoglobinopathies',
'Hemolysis',
'Hemophilia',
'Hemophilia A',
'Hemophilic Arthropathy',
'Hemorrhage',
'Hemorrhagic Disorders',
'Hemorrhagic Fevers, Viral',
'Hemostatic Disorders',
'Hepatic Insufficiency',
'Hepatitis',
'Hepatitis A',
'Hepatitis C',
'Hereditary Autoinflammatory Diseases',
'Heredodegenerative Disorders, Nervous System',
'Herpes Labialis',
'Herpes Simplex',
'Herpes Zoster',
'Herpesviridae Infections',
'Hip Fractures',
'Hip Injuries',
'HIV Infections',
'HIV Seropositivity',
'Hoarseness',
'Hyperadrenalism',
'Hyperaldosteronism',
'Hyperbilirubinemia',
'Hypercapnia',
'Hypereosinophilic Syndrome',
'Hypergammaglobulinemia',
'Hyperglycemia',
'Hyperkinesis',
'Hyperphosphatemia',
'Hyperplasia',
'Hypersensitivity',
'Hypersensitivity, Immediate',
'Hypertension',
'Hypertension, Portal',
'Hypertension, Pregnancy-Induced',
'Hypertension, Pulmonary',
'Hypogonadism',
'Hypokalemia',
'Hyponatremia',
'Hypoparathyroidism',
'Hypothermia',
'Hypotrichosis',
'Hypoventilation',
'Hypoxia',
'Hysteria',
'Iatrogenic Disease',
'Idiopathic Inflammatory Myopathy',
'Idiopathic Interstitial Pneumonias',
'Idiopathic Pulmonary Fibrosis',
'Idiopathic Thrombocytopenic Purpura',
'Immune System Diseases',
'Immune Thrombocytopenia',
'Immunologic Deficiency Syndromes',
'Immunoproliferative Disorders',
'Impulsive Behavior',
'Inclusion Body Myositis',
'Infant, Newborn, Diseases',
'Infant, Premature, Diseases',
'Infarction',
'Infection',
'Infertility',
'Infertility, Female',
'Infertility, Male',
'Inflammation',
'Inflammatory Bowel Diseases',
'Influenza, Human',
'Intellectual Disability',
'Intestinal Atresia',
'Intestinal Diseases',
'Intestinal Neoplasms',
'Intraabdominal Infections',
'Intracranial Embolism',
'Intracranial Embolism and Thrombosis',
'Intracranial Hemorrhages',
'Intracranial Hypertension',
'Intracranial Thrombosis',
'Invasive Fungal Infections',
'Ischemia',
'Jaundice',
'Jaundice, Obstructive',
'Joint Diseases',
'Kawasaki Disease',
'Kennedy Disease',
'Keratitis',
'Keratoconjunctivitis',
'Keratoconjunctivitis Sicca',
'Ketosis',
'Kidney Diseases',
'Kidney Failure, Chronic',
'Kidney Neoplasms',
'Laboratory Infection',
'Lacerations',
'Lacrimal Apparatus Diseases',
'Laryngeal Cancer',
'Laryngeal Diseases',
'Laryngeal Neoplasms',
'Leg Injuries',
'Lens Diseases',
'Lentivirus Infections',
'Leukemia',
'Leukemia, B-Cell',
'Leukemia, Lymphocytic, Chronic, B-Cell',
'Leukemia, Lymphoid',
'Leukemia, Myeloid',
'Leukemia, Myeloid, Acute',
'Leukocyte Disorders',
'Leukocytosis',
'Leukopenia',
'Liver Cirrhosis',
'Liver Cirrhosis, Biliary',
'Liver Diseases',
'Liver Failure',
'Liver Neoplasms',
'Localized Scleroderma',
'Lung Diseases',
'Lung Diseases, Fungal',
'Lung Diseases, Interstitial',
'Lung Diseases, Obstructive',
'Lung Injury',
'Lung Neoplasms',
'Lupus Erythematosus, Systemic',
'Lymphatic Abnormalities',
'Lymphatic Diseases',
'Lymphatic Malformations',
'Lymphedema',
'Lymphoblastic Lymphoma',
'Lymphocytosis',
'Lymphohistiocytosis, Hemophagocytic',
'Lymphoma',
'Lymphoma, B-Cell',
'Lymphoma, Mantle-Cell',
'Lymphoma, Non-Hodgkin',
'Lymphopenia',
'Lymphoproliferative Disorders',
'Lymphosarcoma',
'Macrophage Activation Syndrome',
'Macular Degeneration',
'Macular Edema',
'Malnutrition',
'Mantle Cell Lymphoma',
'Marijuana Abuse',
'Maternal Death',
'Maxillofacial Injuries',
'Measles',
'Medically Unexplained Symptoms',
'Melanoma',
'Memory Disorders',
'Meningitis',
'Meningitis, Bacterial',
'Meningitis, Meningococcal',
'Meningococcal Infections',
'Menopause',
'Menorrhagia',
'Menstruation Disturbances',
'Mental Disorders',
'Mental Fatigue',
'Metabolic Diseases',
'Metabolic Syndrome',
'Microvascular Rarefaction',
'Migraine Disorders',
'Mitochondrial Diseases',
'Monoclonal Gammopathy of Undetermined Significance',
'Mood Disorders',
'Motor Neuron Disease',
'Mouth Diseases',
'Mouth, Edentulous',
'Movement Disorders',
'Mucinoses',
'Mucocutaneous Lymph Node Syndrome',
'Mucormycosis',
'Multiple Chronic Conditions',
'Multiple Myeloma',
'Multiple Organ Failure',
'Multiple Pulmonary Nodules',
'Multiple Sclerosis',
'Muscle Weakness',
'Muscular Atrophy',
'Muscular Diseases',
'Muscular Disorders, Atrophic',
'Muscular Dystrophies',
'Musculoskeletal Abnormalities',
'Musculoskeletal Diseases',
'Musculoskeletal Pain',
'Myalgia',
'Mycobacterium Infections',
'Mycoplasma Infections',
'Mycoses',
'Myelitis',
'Myelitis, Transverse',
'Myelodysplastic Syndromes',
'Myeloproliferative Disorders',
'Myocardial Infarction',
'Myocardial Ischemia',
'Myocardial Reperfusion Injury',
'Myocarditis',
'Myofascial Pain Syndromes',
'Myositis',
'Nausea',
'Necrosis',
'Needlestick Injuries',
'Neisseriaceae Infections',
'Neoplasm Metastasis',
'Neoplasms by Histologic Type',
'Neoplasms, Germ Cell and Embryonal',
'Neoplasms, Glandular and Epithelial',
'Neoplasms, Nerve Tissue',
'Neoplasms, Neuroepithelial',
'Neoplasms, Plasma Cell',
'Neoplastic Cells, Circulating',
'Neoplastic Processes',
'Nephritis',
'Nerve Degeneration',
'Nervous System Neoplasms',
'Neuritis',
'Neurobehavioral Manifestations',
'Neurocognitive Disorders',
'Neurodegenerative Diseases',
'Neurodevelopmental Disorders',
'Neuroectodermal Tumors',
'Neuroectodermal Tumors, Primitive',
'Neuroendocrine Tumors',
'Neuroepithelioma',
'Neurologic Manifestations',
'Neuromuscular Diseases',
'Neuromuscular Manifestations',
'Neuromyelitis Optica',
'Neuromyelitis Optica Spectrum Disorder',
'Neurotoxicity Syndromes',
'Nevi and Melanomas',
'Nevus',
'Nevus, Pigmented',
'Nidovirales Infections',
'Noncommunicable Diseases',
'Nutrition Disorders',
'Obesity',
'Obesity, Morbid',
'Obsessive Behavior',
'Obstetric Labor Complications',
'Obstetric Labor, Premature',
'Occupational Diseases',
'Occupational Stress',
'Oculocerebral Syndrome With Hypopigmentation',
'Olfaction Disorders',
'Opportunistic Infections',
'Optic Nerve Diseases',
'Optic Neuritis',
'Oral Manifestations',
'Orbital Cellulitis',
'Orbital Diseases',
'Orthomyxoviridae Infections',
'Osteoarthritis',
'Osteoarthritis, Hip',
'Osteoarthritis, Knee',
'Osteochondritis',
'Osteoporosis',
'Otitis',
'Otitis Media',
'Otitis Media with Effusion',
'Otorhinolaryngologic Diseases',
'Otorhinolaryngologic Neoplasms',
'Out-of-Hospital Cardiac Arrest',
'Ovarian Cancer',
'Ovarian Diseases',
'Ovarian Epithelial Cancer',
'Ovarian Neoplasms',
'Overnutrition',
'Overweight',
'Pain',
'Pancreatic Cancer',
'Pancreatic Diseases',
'Pancreatic Neoplasms',
'Pancreatitis',
'Panuveitis',
'Paralysis',
'Paramyxoviridae Infections',
'Paraphilic Disorders',
'Paraproteinemias',
'Parasitic Diseases',
'Parasomnias',
'Parathyroid Diseases',
'Paresis',
'Parkinson Disease',
'Parkinsonian Disorders',
'Pathological Conditions, Anatomical',
'Pediatric Obesity',
'Perinatal Death',
'Periodontal Diseases',
'Peripheral Arterial Disease',
'Peripheral Vascular Diseases',
'Peritonitis',
'Perniosis',
'Personality Disorders',
'Pharyngeal Diseases',
'Phlebitis',
'Phobic Disorders',
'Phosphorus Metabolism Disorders',
'Picornaviridae Infections',
'Placenta Diseases',
'Placenta Disorder',
'Pleural Diseases',
'Pleurisy',
'Pleuropneumonia',
'Pleuropneumonia, Contagious',
'Pneumocystis Infections',
'Pneumocystis Jirovecii Pneumonia',
'Pneumocystosis',
'Pneumonia',
'Pneumonia, Bacterial',
'Pneumonia, Pneumocystis',
'Pneumonia, Ventilator-Associated',
'Pneumonia, Viral',
'Pneumoperitoneum',
'Poliomyelitis',
'Polymyalgia Rheumatica',
'Polyps',
'Postoperative Complications',
'Potassium Deficiency',
'Pre-Eclampsia',
'Precursor Cell Lymphoblastic Leukemia-Lymphoma',
'Prediabetic State',
'Pregnancy Complications',
'Pregnancy Complications, Infectious',
'Pregnancy in Diabetics',
'Preleukemia',
'Premature Birth',
'Primary Dysautonomias',
'Primary Lateral Sclerosis',
'Problem Behavior',
'Prostatic Diseases',
'Prostatic Hyperplasia',
'Prostatic Neoplasms',
'Psoriasis',
'Psychological Trauma',
'Psychomotor Agitation',
'Psychophysiologic Disorders',
'Psychotic Disorders',
'Puerperal Disorders',
'Pulmonary Alveolar Proteinosis',
'Pulmonary Arterial Hypertension',
'Pulmonary Atelectasis',
'Pulmonary Disease, Chronic Obstructive',
'Pulmonary Edema',
'Pulmonary Embolism',
'Pulmonary Emphysema',
'Pulmonary Eosinophilia',
'Pulmonary Fibrosis',
'Pulmonary Valve Insufficiency',
'Purpura',
'Purpura, Thrombocytopenic',
'Purpura, Thrombocytopenic, Idiopathic',
'Quality of Life',
'Rare Diseases',
'Rectal Diseases',
'Rectal Neoplasms',
'Recurrence',
'Renal Cell Carcinoma',
'Renal Insufficiency',
'Renal Insufficiency, Chronic',
'Reperfusion Injury',
'Respiration Disorders',
'Respiratory Aspiration',
'Respiratory Distress Syndrome, Adult',
'Respiratory Distress Syndrome, Infant',
'Respiratory Distress Syndrome, Newborn',
'Respiratory Hypersensitivity',
'Respiratory Insufficiency',
'Respiratory Syncytial Virus Infections',
'Respiratory Tract Diseases',
'Respiratory Tract Infections',
'Respiratory Tract Neoplasms',
'Restless Legs Syndrome',
'Retinal Degeneration',
'Retinal Diseases',
'Retinal Vein Occlusion',
'Retroviridae Infections',
'Rheumatic Diseases',
'Rheumatic Fever',
'Rhinitis, Allergic, Seasonal',
'RNA Virus Infections',
'Rumination Disorder',
'Rupture',
'Salivary Gland Diseases',
'Sarcoidosis',
'Sarcopenia',
'Schizophrenia',
'Schizophrenia Spectrum and Other Psychotic Disorders',
'Schizotypal Personality Disorder',
'Scleroderma, Diffuse',
'Scleroderma, Localized',
'Scleroderma, Systemic',
'Sclerosis',
'Seizures',
'Self-Injurious Behavior',
'Sensation Disorders',
'Sepsis',
'Severe Acute Respiratory Syndrome',
'Sexual Dysfunction, Physiological',
'Sexual Dysfunctions, Psychological',
'Sexually Transmitted Diseases',
'Sexually Transmitted Diseases, Viral',
'Shock',
'Shock, Cardiogenic',
'Shock, Septic',
'Shoulder Impingement Syndrome',
'Shprintzen-Goldberg Craniosynostosis Syndrome',
'Sickle Cell Anemia',
'Signs and Symptoms, Digestive',
'Signs and Symptoms, Respiratory',
"Sjogren's Syndrome",
'Skin Diseases',
'Skin Diseases, Genetic',
'Skin Diseases, Infectious',
'Skin Diseases, Papulosquamous',
'Skin Diseases, Vesiculobullous',
'Skin Diseases, Viral',
'Skin Manifestations',
'Skin Neoplasms',
'Skull Fractures',
'Sleep Apnea Syndromes',
'Sleep Apnea, Obstructive',
'Sleep Disorders, Intrinsic',
'Sleep Initiation and Maintenance Disorders',
'Sleep Wake Disorders',
'Slow Virus Diseases',
'Somatoform Disorders',
'Spinal Cord Diseases',
'Spinal Cord Injuries',
'Spinal Diseases',
'Spondylarthritis',
'Spondylarthropathies',
'Spondylitis',
'Sprains and Strains',
'ST Elevation Myocardial Infarction',
'Status Epilepticus',
'Stillbirth',
'Stomach Cancer',
'Stomach Diseases',
'Stomach Neoplasms',
'Stomatognathic Diseases',
'Storm Syndrome',
'Streptococcal Infections',
'Stress Disorders, Post-Traumatic',
'Stress Disorders, Traumatic',
'Stress Disorders, Traumatic, Acute',
'Stress, Psychological',
'Stroke',
'Subarachnoid Hemorrhage',
'Subcutaneous Emphysema',
'Substance-Related Disorders',
'Suicidal Ideation',
'Suicide',
'Superinfection',
'Suppuration',
'Syndrome',
'Synovial Cyst',
'Systemic Inflammatory Response Syndrome',
'Systemic Scleroderma',
'Tachycardia',
'Tachycardia, Ventricular',
'Taste Disorders',
'Tauopathies',
'TDP-43 Proteinopathies',
'Testicular Diseases',
'Testicular Neoplasms',
'Thalassemia',
'Thoracic Diseases',
'Thoracic Injuries',
'Thoracic Neoplasms',
'Thrombocytopenia',
'Thromboembolism',
'Thrombophilia',
'Thrombophlebitis',
'Thrombosis',
'Thrombotic Microangiopathies',
'Tic Disorders',
'Tics',
'Tobacco Use Disorder',
'Tooth Diseases',
'Torsades de Pointes',
'Tourette Syndrome',
'Toxemia',
'Transitional Cell Carcinoma',
'Trauma and Stressor Related Disorders',
'Trauma, Nervous System',
'Tuberculosis',
'Turcot Syndrome',
'Ulcer',
'Urinary Bladder Neoplasms',
'Urinary Tract Infections',
'Urogenital Neoplasms',
'Urologic Diseases',
'Urologic Neoplasms',
'Urticaria',
'Uterine Cervical Diseases',
'Uterine Cervical Neoplasms',
'Uterine Diseases',
'Uterine Hemorrhage',
'Uterine Neoplasms',
'Uveal Diseases',
'Uveitis',
'Uveitis, Anterior',
'Vaginal Cancer',
'Vaginal Diseases',
'Vaginal Neoplasms',
'Varicella Zoster Virus Infection',
'Varicose Veins',
'Vascular Diseases',
'Vasculitis',
'Vasculitis, Central Nervous System',
'Venous Thromboembolism',
'Venous Thrombosis',
'Ventilator-Induced Lung Injury',
'Ventricular Dysfunction',
'Ventricular Dysfunction, Left',
'Ventricular Dysfunction, Right',
'Ventricular Outflow Obstruction',
'Viral Hemorrhagic Fever',
'Virus Diseases',
'Visceral Steatosis',
'Vision Disorders',
'Vision, Low',
'Vitamin D Deficiency',
'Voice Disorders',
'Vulvar Cancer',
'Vulvar Diseases',
'Vulvar Neoplasms',
'Water-Electrolyte Imbalance',
'Weight Gain',
'Weight Loss',
'Wounds and Injuries',
'Wounds, Penetrating',
'Xerostomia',
'Yellow Fever',
'Zygomycosis'
]
disease_list_small = [
    'Appendicitis',
'Arbovirus Infections',
'Arrhythmias, Cardiac',
'Atherosclerosis',
'Atrial Fibrillation',
'B-cell Lymphoma'
]